spring:
  application:
    name: transaction-service

  server:
    port: 8080

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      topic: authentication
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    group-id: transaction
